### ISSUE TITLE
Does not work on hooks for me

### ISSUE THREAD

**Issue by hgeissler** [Kocal/jsdoc-vuejs#240] opened 2019-07-16 13:34 UTC
```
/**
  * Counter.vue `created` hook.
  */
created() {
  console.info('Counter.vue: created()');
},
```

^ For me this code-snippet from your example does not work. It is not getting parsed into the documentation.
I'm using vue version 2.6.10

**Comment by Kocal** [comment] 2019-07-30 18:58
Duplicate of #95

**Closed by Kocal** 2019-07-30 18:58 UTC
