### ISSUE TITLE
JSDoc description for 'data' and 'computed'.

### ISSUE THREAD

**Issue by kryvonos-v** [Kocal/jsdoc-vuejs#2] opened 2017-08-31 12:06 UTC
Hey, there!

Is it possible somehow to add JSDoc description for 'computed' and 'data''? I would really like to have this kind of functionality.

**Comment by Kocal** [comment] 2017-08-31 16:54
Hey,

It's something I want to see but it's not already implemented.
Do you have an idea how we can write a description for "computed" and "data"?

I have two ideas for now.

The first with a new tag named `vueData`
```js
/**
 * @vue
 * @vueData counter The counter value
 */
export default {
  data () {
    return {counter: 0}
  }
}
```

or the second by modifying Vue, but I don't want to do that.

```js
/**
 * @vue
 */
export default {
  data () {
    return [
      { name: 'counter', value: 0, description: 'The counter value'}
    ]
  }
}
```

**Comment by Kocal** [comment] 2017-08-31 16:56
Or maybe something like
```js
/**
 * @vue
 * @vueData counter The counter value
 */
export default {
  data () {
    return {counter: 0}
  }
  jsdoc: {
    data: {
      counter: 'The counter value',
    },
    // computed, props, ...
  }
}
```

I think this one is better

**Comment by Kocal** [comment] 2017-08-31 18:48
A more complex example:

```js
/**
 * @vue
 */
export default {
  data () {
    return {counter: 0}
  }
  jsdoc: {
    data: {
      counter: {
        description: 'The counter value',
        type: Number,
      },
    },
    // computed, props, ...
  }
}
```

**Comment by Kocal** [comment] 2018-06-15 06:03
I'm working on this feature in v2.

Duplicate of #48, I'm closing.

**Closed by Kocal** 2018-06-15 06:03 UTC
